add missing semicolon to fix C syntax
dbdimp.c: In function 'ib_st_fetch':
dbdimp.c:1389:21: error: expected ';' before 'break'
 1389 |                     break;
      |                     ^~~~~